// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtBzEw9YYYXgtSpDIzZ9R_eH8z57Glt_0',
    appId: '1:1098903549218:android:53cffa789870b4d22be17b',
    messagingSenderId: '1098903549218',
    projectId: 'team-i-radiations',
    storageBucket: 'team-i-radiations.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHtkt-RO2U0kxpclVeOibGkLx7tOeqRTs',
    appId: '1:1098903549218:ios:e86d11e61e4167d62be17b',
    messagingSenderId: '1098903549218',
    projectId: 'team-i-radiations',
    storageBucket: 'team-i-radiations.appspot.com',
    iosClientId: '1098903549218-vttdeut9r2arv21q46ohfua7jrhhpp3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHtkt-RO2U0kxpclVeOibGkLx7tOeqRTs',
    appId: '1:1098903549218:ios:e86d11e61e4167d62be17b',
    messagingSenderId: '1098903549218',
    projectId: 'team-i-radiations',
    storageBucket: 'team-i-radiations.appspot.com',
    iosClientId: '1098903549218-vttdeut9r2arv21q46ohfua7jrhhpp3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
